// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frjilckrskfhdejsrijd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyamlsY2tyc2tmaGRlanNyaWpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMzIxOTgsImV4cCI6MjA2MDYwODE5OH0.KjuAP6fcO9TE4SdN07MBNabng5RzsQyUQPGyNPde-XY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);